// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  featured_categories: dynamic(() => import("./FeaturedCategories")),
  featured_recipes: dynamic(() => import("./FeaturedRecipes")),
  how_to: dynamic(() => import("./HowTo")),
  image: dynamic(() => import("./Image")),
  ingredient_kit: dynamic(() => import("./IngredientKit")),
  ingredients: dynamic(() => import("./Ingredients")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  text: dynamic(() => import("./Text")),
};
